### ISSUE TITLE
When logging in, double tapping the emoji causes a black screen in the app.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/3Bot_connect#43]
**Repro steps**
1) Go to freeflowpages and trigger a login for an existing account
2) Enter pin and while selecting the correct emoji, double tap it.

**Expected Result**
Logged in

**Actual Result**
Black screen

**System Info**
ADDITIONAL INFORMATION
Updated
January 15, 2020
Size
4.0M
Installs
500+
Current Version
1.4.3

**Comment by MathiasDeWeerdt** [comment]
Fixed

**Comment by ken-de-moor** [comment]
still happens on 

Type: Staging 
Git user: Mathias De Weerdt 
Git branch: v1.4.4 
Git hash: ca37da7 
Time: 11:19:49 31.01.2020
